# Generated by Django 5.2.8 on 2025-11-19 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Остатки на складе', 'verbose_name_plural': 'Остатки'},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='quantity_in_stock',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход'), ('ADJ', 'Корректировка')], max_length=3, verbose_name='Тип операции')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Движение по складу',
                'verbose_name_plural': 'Движения по складу',
                'ordering': ['-created_at'],
            },
        ),
    ]
