# Generated by Django 5.2.8 on 2025-11-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
