# Generated by Django 5.2.8 on 2025-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_warehouse_options_warehouse_quantity_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Не указан', max_length=255, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
