# Generated by Django 5.2.8 on 2025-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Не оплачен'), ('Paid', 'Оплачен')], default='Unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
